### ISSUE TITLE
关于测试代码

### ISSUE THREAD

**Issue by Like-h** [IkeYang/machine-vision-assisted-deep-time-series-analysis-MV-DTSA-#2]
请问运行完main之后是不是没有测试啊？需要运行test吗？我运行test之后没有回显任何结果

**Comment by IkeYang** [comment]
不用呀，运行main会输出每个epoch的验证集和测试集的测试结果

**Comment by Like-h** [comment]
谢谢。您是说，最后一个epoch的结果就是最终的测试集结果嘛？介不介意加个联系方式咨询一下

**Comment by Like-h** [comment]
您好，抱歉我的上一个问题很愚蠢。我想请问一下，关于损失函数中，为什么计算的是预测输出和d的距离？不太理解d代表什么

**Comment by IkeYang** [comment]
D代表EMD距离 具体理论细节请参考原论文

**Comment by Like-h** [comment]
我在ETTm2上复现不出来结果。请问您有当时的实验参数数据之类的嘛，我的测试集结果差了很多

**Comment by IkeYang** [comment]
我用默认参数训练第一个epoch输出如下：

> 2023-05-31 17:25:21.586889
> PID:  4428 ***********
> Namespace(Norm_Insequence=True, TA=0.9, TAP=3, bs=16, dNorm=1, data_path='ETTm2.csv', dropout=0.1, features='M', flag='train', h=200, loss='EMD', maxScal=2.79, maxTest=500, modelAda=False, modelName='DeepLabMobIndependent', modelSize=4, num_workers=0, reducedChannelNumber=None, size=[336, 0, 96], target='OT', weight_decay=0)
> AdaFactor 0.2 input_channel 6
> [0/10][0/2134]	Loss: 2.87863064	  
> [0/10][533/2134]	Loss: 1.23762226	  
> [0/10][1066/2134]	Loss: 1.31593990	  
> [0/10][1599/2134]	Loss: 1.35508418	  
> [0/10][2132/2134]	Loss: 1.15324140	  
> Validation......
> 0
> MAX MSE= 0.12378622671136877 RMSE= 0.3518326686244027 715
> MAX MAE= 0.2376488362280384 MSE_expection= 0.2367536537401326
> Expection MSE= 0.1225324921257846 RMSE= 0.3500464142450035 715
> Expection MAE= 0.2367536537401326 RMSE= 0.48657337960489844 715
> Testing......
> 0
> MAX MSE= 0.1779854112970911 RMSE= 0.42188317256924474 715
> MAX MAE= 0.25328056049927355 MSE_expection= 0.25198593137564357
> Expection MSE= 0.17467027518872197 RMSE= 0.41793573093087166 715
> Expection MAE= 0.25198593137564357 RMSE= 0.5019820030395946 715
其中Expection MSE= 0.1746 Expection MAE= 0.2519 接近我们宣称的
> 0.170 0.244
如果你多跑几个epoch以及多采用几组训练参数或者使用更新的优化器以及学习策略 可以轻松打破我们的实验精度，我们的结果其实也没有仔细调参

**Comment by Like-h** [comment]
我第一个epoch是0.175，但是越跑这个MSE越大，第十个epoch都0.210了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 晚上6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IkeYang/machine-vision-assisted-deep-time-series-analysis-MV-DTSA-] 关于测试代码 (Issue #2)





 
我用默认参数训练第一个epoch输出如下：
  
2023-05-31 17:25:21.586889
 PID:  4428 ***********
 Namespace(Norm_Insequence=True, TA=0.9, TAP=3, bs=16, dNorm=1, data_path='ETTm2.csv', dropout=0.1, features='M', flag='train', h=200, loss='EMD', maxScal=2.79, maxTest=500, modelAda=False, modelName='DeepLabMobIndependent', modelSize=4, num_workers=0, reducedChannelNumber=None, size=[336, 0, 96], target='OT', weight_decay=0)
 AdaFactor 0.2 input_channel 6
 [0/10][0/2134]	Loss: 2.87863064
 [0/10][533/2134]	Loss: 1.23762226
 [0/10][1066/2134]	Loss: 1.31593990
 [0/10][1599/2134]	Loss: 1.35508418
 [0/10][2132/2134]	Loss: 1.15324140
 Validation......
 0
 MAX MSE= 0.12378622671136877 RMSE= 0.3518326686244027 715
 MAX MAE= 0.2376488362280384 MSE_expection= 0.2367536537401326
 Expection MSE= 0.1225324921257846 RMSE= 0.3500464142450035 715
 Expection MAE= 0.2367536537401326 RMSE= 0.48657337960489844 715
 Testing......
 0
 MAX MSE= 0.1779854112970911 RMSE= 0.42188317256924474 715
 MAX MAE= 0.25328056049927355 MSE_expection= 0.25198593137564357
 Expection MSE= 0.17467027518872197 RMSE= 0.41793573093087166 715
 Expection MAE= 0.25198593137564357 RMSE= 0.5019820030395946 715
 其中Expection MSE= 0.1746 Expection MAE= 0.2519 接近我们宣称的
 0.170 0.244
 如果你多跑几个epoch以及多采用几组训练参数或者使用更新的优化器以及学习策略 可以轻松打破我们的实验精度，我们的结果其实也没有仔细调参

**Comment by IkeYang** [comment]
你可以调整下学习率，bs，优化器的动量系数，等等, 训练调参的问题麻烦多试试
